[providers]
python = "3.13"

[phases.setup]
nixPkgs = ["python313", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:asgi_app --host 0.0.0.0 --port $PORT"

